[tox]
envlist = py{27,35,36}, flake8
skip_missing_interpreters = true

[testenv:py27]
setenv =
  GIRDER_USER={env:GIRDER_USER:}
  GIRDER_PASSWORD={env:GIRDER_PASSWORD:}
deps = -rrequirements2.txt
commands = pytest tests/test_girder_contents_api.py::GirderContentsTest -k "not test_checkpoints_follow_file"

[testenv:py36]
setenv =
  GIRDER_USER={env:GIRDER_USER:}
  GIRDER_PASSWORD={env:GIRDER_PASSWORD:}
deps = -rrequirements3.txt
commands = pytest tests/test_girder_contents_api.py::GirderContentsTest -k "not test_checkpoints_follow_file"

[testenv:flake8]
skip_install = true
deps =
  flake8
  flake8-blind-except
  flake8-docstrings
  flake8-quotes
commands = flake8 {posargs}

[flake8]
exclude = tests/ansible/
max-line-length: 100
# Whether to show source code for each failure
show-source: True
# Maximum cyclomatic complexity allowed
max-complexity: 14
format: pylint
# Ignore certain errors.
#
#   If an ignore line is not specified, the pep8 module defaults to
#     E123,E133,E226,E241,E242.
#   We didn't have any E133 or E242 errors, so don't ignore those.
#
# The errors we suppress are:
#   Whitespace errors
#   ~~~~~~~~~~~~~~~~~
#     E123 - closing bracket does not match indentation of opening bracket's
#            line
#     E226 - missing whitespace around arithmetic operator
#     E241 - multiple spaces after ","
#     W503 - line break occurred before a binary operator
#
#   Docstring errors
#   ~~~~~~~~~~~~~~~~
#   By including the flake8-docstrings module, we also will fail on PEP257
#   errors (D...).  For the moment, suppress all of the D... errors that would
#   cause us to fail.  We may want to revisit this to make our code more PEP257
#   conformant.
#     D100 - Public module   (100) docstring missing.
#     D101 - Public class    (101) docstring missing.
#     D102 - Public method   (102) docstring missing.
#     D103 - Public function (103) docstring missing.
#     D104 - Missing docstring in public package.
#     D105 - Missing docstring in magic method.
#     D106 - Missing docstring in public nested class
#     D107 - Missing docstring in __init__
#     D200 - One-line docstrings should fit on one line with quotes.
#     D201 - No blank lines allowed before (201) docstring.
#     D202 - No blank lines allowed after  (202) docstring.
#     D203 - 1 blank required before (203) class docstring.
#     D204 - 1 blank required after  (204) class docstring.
#     D205 - Blank line required between one-line summary and description.
#     D400 - First line should end with a period.
#     D401 - First line should be in imperative mood.
#     D402 - First line should not be the function's "signature".
#
#   Identifier errors
#   ~~~~~~~~~~~~~~~~~
#   TODO(opadron) we should have an explanation of why we break away from normal
#   Python naming conventions.  Is this a case of the prevailing style argument
#   made in pep8?  If so, exactly who's style is prevailing?
#     N802 - Function name should be lowercase.
#     N803 - Argument name should be lowercase.
#     N806 - Variable in function should be lowercase.
#     N812 - Lowercase imported as non lowercase.
ignore: D100,D101,D102,D103,D104,D105,D106,D107,D200,D201,D202,D203,D204,D205,D400,D401,D402,E123,E226,E241,N802,N803,N806,N812,W503

